version: 2
jobs:
   test:
     docker:
       - image: circleci/node:6
     steps:
       - checkout
       - run: git config --global user.name "Mona Lisa" && git config --global user.email "email@example.com"
       - run: yarn
       - run: node_modules/.bin/bats tests/

   release:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
      - run: yarn publish --new-version="$CIRCLE_TAG" --no-git-tag-version

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: org-global